# Processor frequency (external freq-in)
ifndef F_CPU
F_CPU = 7372800
endif

HALPATH = $(FIRMWAREPATH)/hal
VPATH += :$(HALPATH)

#Default stuff
EXTRAINCDIRS += $(HALPATH)

HAL = stm32l0
PLTNAME = STM32L0 Target
PLATFORM = STM32L0

include $(HALPATH)/$(HAL)/Makefile.$(HAL)

CDEFS += -DHAL_TYPE=HAL_$(HAL) -DPLATFORM=$(PLATFORM)